### ISSUE TITLE
No module named data_slicer.tests.run_tests

### ISSUE THREAD

**Issue by brixel-1984** [kuadrat/data-slicer#16]
Hello,

I just installed data-slicer and tried to run the initial tests you recommend to check this installation but I get the following error msg:
'No module named data_slicer.tests.run_tests'
The same occurs when I try to run the tests individually (pit, freeslice, etc.)
I quickly checked the list of packages installed and noticed that the default installation, at least on my machine, did not include two packages: pytest and pytest-qt.
I installed them, but the same error message pops up.

I am not sure that this necessarily means that the installation did not proceed as it should, but when I load the Python image tool, I do not see any data...

Any idea what could be the issue?

Bernard
Ps: I installed data-slicer on a dedicated conda environment, with python 3.7.5. I run a Windows 10 machine.

**Comment by kuadrat** [comment]
Hi Bernard,

sorry for letting you wait for half a year. Maybe you are still interested in this.

Judging from the error message I don't think the problem was the missing `pytest` and `pytest-qt` packages, but rather something more fundamental with the installation. Did the installation complete with something like `Successfully installed data_slicer`? Can you run a python script with the only line being `import data_slicer`?

Best,
Kevin

**Comment by brixel-1984** [comment]
No worries, Kevin!
Thanks for getting back to me. I re-installed it and it works like a charm.
Best
Bernard
